//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZZCraft.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CraftItems
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Count { get; set; }
        public int IdRecipe { get; set; }
    
        public virtual Recipe Recipe { get; set; }
    }
}
