//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZZCraft.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InitialDrops
    {
        public int ID { get; set; }
        public int iDInitialRes { get; set; }
        public int Counts { get; set; }
    
        public virtual InitialRes InitialRes { get; set; }
    }
}
