//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZZCraft.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.CraftItems = new HashSet<CraftItems>();
        }
    
        public int id { get; set; }
        public Nullable<int> objectOne { get; set; }
        public Nullable<int> objectTwo { get; set; }
        public Nullable<int> objectThree { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CraftItems> CraftItems { get; set; }
        public virtual InitialRes InitialRes { get; set; }
        public virtual InitialRes InitialRes1 { get; set; }
        public virtual InitialRes InitialRes2 { get; set; }
    }
}
